INSERT INTO VEHICLEDTO VALUES (10,'MH001','Sahil Shah');
INSERT INTO VEHICLEDTO VALUES (9,'MH002','sam');
INSERT INTO VEHICLEDTO VALUES (11,'MH025','Mayur');
INSERT INTO VEHICLEDTO VALUES (08,'MH00','Test');
INSERT INTO VEHICLEDTO VALUES (61,'MH025','Java');