spring:
  security:
    oauth2:
      client:
        registration:
          facebook:
            client-id: 
            client-secret: 
            scope: public_profile email user_location
          google:
            client-id: 566746547955-p61061irrafjgv1mh0lh77t0ss72tg1i.apps.googleusercontent.com
            client-secret: TIaTzstyZl8KZ6h35tiAVuHm 
logging:
  level:
    root: INFO
    com.memorynotfound: INFO
    org.springframework.web: INFO
    org.springframework.security: INFO
